### ISSUE TITLE
Not worked toggleSpanStyle

### ISSUE THREAD

**Issue by v1rus-dev** [MohamedRejeb/Compose-Rich-Editor#85] opened 2023-08-03 19:38 UTC
Not worked toggleSpanStyle if you try set textDecoration like null.

Below my code for changing underline:
`fun RichTextState.isUnderline(): Boolean =
    currentSpanStyle.textDecoration == TextDecoration.Underline`
`fun RichTextState.toggleUnderlineFont() {
    toggleSpanStyle(
        SpanStyle(
            textDecoration = if (isUnderline()) {
                null
            } else {
                TextDecoration.Underline
            }
        )
    )
}`

If i set textDecoration like Underline this is work, not work if i set null.

**Comment by MohamedRejeb** [comment] 2023-08-03 19:54
Thanks for reporting this issue, I'll check it

**Comment by MohamedRejeb** [comment] 2023-08-05 07:03
There's nothing like textDecoration null, what you are trying to achieve exactly ? if you want to remove the textDecoration you can use removeSpanStyle(currentSpanStyle.textDecoration)

**Comment by v1rus-dev** [comment] 2023-08-07 18:35
Yes, I already understood, but for this I had to look at the documentation. It was just logical to set null, since by default the value is null.

**Comment by MohamedRejeb** [comment] 2023-08-08 05:24
Yeah that's try, but the problem with that approach is that you are passing a default `SpanStyle()` that contains all the parameters as null not just the `textDecoration` so this is going to reset every style not just `textDecoration`.
That's why I'm ignoring the null and non specified parameters to avoid similar problems like reseting styling that you don't want to reset.

**Comment by MohamedRejeb** [comment] 2023-08-11 10:13
I'm going to close this issue since it's not a bug. I will try to explain this more in docs. Also feel free to write a comment if you have any suggestions or questions.

**Closed by MohamedRejeb** 2023-08-11 10:13 UTC
